### Target Datasets
target_datasets:
  - name: BBBC039

### Source Models
source_models:
  - source_name: BBBC039 
    model_name: BC_IN_model
  - source_name: S_BIAD895
    model_name: 895_IN_model

### Perturbation Settings

# Feature perturbations
feature_perturbations:
  random_seed: 42
  layers: [0]
  spatial_dropout: True
  perturbation_types:
    - "None"
    - "DropOutPerturbation"
  dropOut_rates:
    - 0.1
    - 0.2
  featureDrop_thresholds: null
  featureNoise_ranges: null 

# Input Augmentations
input_augs:
    none: []

### General Run Settings
overwrite_yaml: True
segmentation_mode: instance
run_mode: full
data_base_path: /path/to/data/directory
model_dir_path: /g/kreshuk/talks/Models
summary_results:
  overwrite_scores: False

# Output Settings
output_settings:
  result_dir: example_run
  approach: feature_perturbation_consistency
  base_dir_path: /path/to/repo/examples/example_batch_run/output_structure


### Performance and Consistency evaluation settings
eval_settings:
  name: MeanAvgPrecision
  eval_save_key: MAP_eval
  overwrite_score: False

consistency_settings:
  name: AdaptedRandError
  save_key: ARE_consis
  save_mask: True
  mask_threshold: null
  overwrite_score: False
