name: CRank

channels:
  - pytorch
  - conda-forge
  - nvidia
  - nodefaults

dependencies:
  - h5py
  - imageio
  - ipykernel
  - matplotlib
  - numpy
  - pathlib
  - pip
  - plant-seg
  - pydantic
  - pytest
  - pytorch
  - pytorch-cuda=12.1
  - pyyaml
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools
  - tensorboard
  - tqdm
  - typer
  - typing
  - wandb

  - pip:
      - torcheval
      - git+https://github.com/Josh-Talks/pytorch-3dunet.git@1.8.7-model_ranking#egg=pytorch3dunet
      - -e .

