### Target Datasets
target_datasets:
  - name: BBBC039
  - name: DSB2018
  - name: Hoechst

### Source Models
source_models:
  - source_name: BBBC039 
    model_name: BC_IN_model
  - source_name: S_BIAD895
    model_name: 895_IN_model

### Perturbation Settings

# Feature perturbations
feature_perturbations:
  random_seed: 42
  layers: [0]
  spatial_dropout: True
  perturbation_types:
    - "None"
    - "DropOutPerturbation"
  dropOut_rates:
    - 0.05
    - 0.1
    - 0.2
    - 0.3
    - 0.4
  featureDrop_thresholds: null
  featureNoise_ranges: null 

# Input Augmentations
input_augs:
    none: []

### General Run Settings
overwrite_yaml: True
segmentation_mode: instance
run_mode: full
data_base_path: /path/to/data/directory
model_dir_path: /path/to/model/directory
summary_results:
  overwrite_scores: False

# Output Settings
output_settings:
  result_dir: run_name
  approach: feature_perturbation_consistency
  base_dir_path: /path/to/output/directory


### Performance and Consistency evaluation settings
eval_settings: null

consistency_settings:
  name: AdaptedRandError
  save_key: ARE_consis
  save_mask: True
  mask_threshold: null
  overwrite_score: False
